class_name: ensertainty.training.EnsembleTrainer
checkpoints: ['full_path_to_model_checkpoint_1', 'full_path_to_model_checkpoint_2'] 
checkpoints_models: ['model.eqx', 'model.eqx'] # model.eqx is the default name of the model checkpoint and the array should contain the same number of elements as the checkpoints array 
checkpoints_states: ['state.pickle', 'state.pickle'] # state.pickle is the default name of the state checkpoint and the array should contain the same number of elements as the checkpoints array
