defaults:
  - _self_
  - logging: wandb
  - inference: reconstructions
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

general:
  run_name: RECONSTRUCTIONS
  logs_folder_name: logs
  model_checkpoints_path: /work3/s210527/ensertainty/experiments/${general.run_name}/
  workspace: dmiai-mh
  project_name: ens_vae_reconstructions
  log_code: False
  save_best: True

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
