defaults:
  - _self_
  - datamodule: mnist_2class
  - logging: wandb
  - loss: l2loss
  - metric: null
  - model: ensemble_vae
  - encoder: basic_dense
  - decoder: basic_dense
  - optimizer: adam
  - scheduler: constant
  - grad_clipping: global_norm
  - training: train
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

general:
  run_name: run
  logs_folder_name: logs
  model_checkpoints_path: ./model_checkpoints/${general.project_name}/${general.run_name}/
  workspace: dmiai-mh
  project_name: ens_vae_training
  log_code: False
  save_best: True

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
    #subdir: ${now:%Y-%m-%d_%H-%M-%S}_${hydra.job.num}_${datamodule.fold_n}