class_name: ensertainty.nn.ModifiedConvEncoder
params:
  h: ${datamodule.height}
  w: ${datamodule.width}
  channels_in: ${datamodule.channels}
  out_features: ${model.latent_dim}
  levels: 4
  channels_multiplier: 5
